### ISSUE TITLE
No option to set trader to level 0 / disable it

### ISSUE THREAD

**Issue by Faalagorn** [kokarn/tarkov-tools#104]
First of all, thanks for creating the page and leaving the source code on GitHub

I have no idea how hard is is to add, but currently, you can't choose level 0 / disable Jaeger, while it requires finishing a quest to do so, so it's possible to not have it unlocked.

While at it, Fence also have 1-4 options while he actually only have level 1 as well as master (4) available in game, though I think it doesn't do anything for the site and would probably be worth opening a separate issue for it.

**Comment by kokarn** [comment]
You're welcome! Trying to do my best to provide some value for the community.

Nice find with Jaeger actually! 
That makes sense to be able to disable him until he's unlocked.

I'll keep the Fence stuff in mind but yeah, should probably be another issue 👍
