### ISSUE TITLE
Show and include buy price from Fence

### ISSUE THREAD

**Issue by Faalagorn** [kokarn/tarkov-tools#107]
As an account with no access to Flea Market, I often scourge Fence for deals. I also wonder what barters or hideout crafts I can do that are profitable from items bought on Fence.

Is it possible to include the price from Fence in the site and show them accordingly in the profitable crafts if one doesn't have access to flea market?

**Comment by kokarn** [comment]
Sadly, no. 

Mainly because the inventory of Fence changes every time you look at his inventory. 
So even tho we could in theory have the prices from him there, by the time you try to buy the item it's no longer available :)

**Comment by Faalagorn** [comment]
> Sadly, no.
> 
> Mainly because the inventory of Fence changes every time you look at his inventory. So even tho we could in theory have the prices from him there, by the time you try to buy the item it's no longer available :)

Yeah, I know that things bought from Fence disappear quickly, but I'd love to know whether I can craft something profitable from here, but my case is isolated so it's quite understandable as you can't count on it and can't be used as a reliable income of any kind :).

Do you at least know the base item price modifier fence pays for buying and selling, so at least I could approximate that?

**Comment by kokarn** [comment]
Yeah, for sure. It's documented in the code as well. He buys for 0.4 of the baseValue of the item. Selling prices is not something that's public as far as I know.

**Comment by Faalagorn** [comment]
> Yeah, for sure. It's documented in the code as well. He buys for 0.4 of the baseValue of the item. Selling prices is not something that's public as far as I know.

Thank you! I asked, as the barter trades listed on the site was really helping me finding items to buy on Fence helping me moving forward upgrading my hideout while playing on Linux – since BattlEye doesn't yet fully work, the game keeps crashing right before entering the online raid, both as Scav and as PMC and I'm stubborn on not playing on Linux, the only way to move forward and make money, not including the starting gear, starting Prapor gifts, old book gifts and Twitch drops are either hideout, barters, sporadic daily quests, or flea market for FIR items from hideout as well as Gunsmith task(s), though that require a lot of money to get XP from healing with first aids.

In the end, it made for an interesting "play style", and I figured it out by buying the barters and hideout with the highest profits listed on the site. :)
