### ISSUE TITLE
Market search is very inaccurate

### ISSUE THREAD

**Issue by scainburger** [kokarn/tarkov-tools#108]
Searching for items, for example in this case "Emercom", shows seemingly random items.

https://i.imgur.com/0x7g2pN.png

Adding more nonsense text after the search term does seem to make the filter apply correctly after a certain point.

https://i.imgur.com/QfC8Btx.png

**Comment by kokarn** [comment]
Tried this out, and this does not seem to be an issue with the site as it is right now. 

However, there was a bit of a search issue a little while back that did save some data in an incompatible way that caused this to happen.

If you open another browser or an incognito window, do you get the same behaviour? 
If that's the case I have some ideas on what to fix.


![chrome-capture (1)](https://user-images.githubusercontent.com/1373940/143831603-5b815d40-1c9a-427b-9e39-6904255d1f5d.gif)

**Comment by scainburger** [comment]
Yep, looks like it works correctly in incognito for me.

**Comment by Akiyamov** [comment]
You have sorting by name on, it breaks search. Without it everything okay as you can see in incognito

**Comment by kokarn** [comment]
I'll push a fix to "reset" the sorting so people don't get stuck with the old behaviour. 

Might even be a good solution to disable name-sorting when searching, no sure.

**Comment by scainburger** [comment]
Resetting the sorting in my main window did indeed fix it. Thanks for the heads up.

Although, a bit of feedback: when I'm searching for "Emercom", I'm not sure why other items that don't have that word in their name show up. I can't imagine I'd ever be interested in seeing TarCola, Esmarch, Electric motor etc in this case.

**Comment by Faalagorn** [comment]
Well, I had the same issue for a while, didn't troubleshoot it further, it was easy to just Google the item name when I wanted to look things up and now I see the same issue was reported here.

It seems to be better now, at least I can find items by typing the name, but I find it weird that typing each letter shuffles the sorting each time a letter is being put.

**Comment by kokarn** [comment]
The reason other items show up is that the matching is fuzzy to match stuff like "enercom" or "emmercom" for example.

I've pushed more changes to the search that should both reset the search for every user and also disables name search in some scenarios.

**Comment by kokarn** [comment]
This seems to work much better now, I'll consider this closed for now
