### ISSUE TITLE
"Has flea" and Stations set to "Not built" reset to their default values

### ISSUE THREAD

**Issue by Faalagorn** [kokarn/tarkov-tools#109]
It seems that while other settings that I have set – in particular hideout management and crafting skill levels as well as stations that I set to 1 (and traders too, while I have them on default values, I just tested that when I change value, they stay) are being remembered, when I refresh the page, the "Has flea" resets to enabled and the stations that I set to "Not built" are being set to the max level which are the default values.

EDIT: Forgot to mention, I'm on Firefox.
EDIT2: Just tested it on Chromium though, it seems to behave the same.

EDIT3: I should also mention, that these option do work if you navigate away from the page (close the page or open another tab), but it gets reset and automatically each time you visit the page (either by clicking F5 to reload or click the gear icon at any point of browsing the website, e.g. to update your preferences).

**Comment by kokarn** [comment]
Pushed a lot of changes related to the settings page and I can no longer reproduce this.

Do you still see the same behaviour on your end?

**Comment by Faalagorn** [comment]
I did a little testing and while I refresh the page it starts with "Has flea" enabled for a second, it then switches off. I also tried with tarkovtracker API and it seems to successfully pull the market information from my profile, so unless there's something I miss and maybe refreshes a little slow, it seems to be fixed, thanks!

**Comment by kokarn** [comment]
Glad this can be solved! Sorry for the sloppy initial implementation

**Comment by Faalagorn** [comment]
Well, it did reset for me now, though after I went to settings, and navigating back it is back to being good. There's still some awkwardness, maybe it didn't pull the data from tracker, but definitely better than the last time :)
