### ISSUE TITLE
Barter profits tab shows Jaeger even when disabled

### ISSUE THREAD

**Issue by Faalagorn** [kokarn/tarkov-tools#110]
Even when Jaeger is disabled as a trader, the Barter profits tab still shows his exchanges.

EDIT: Actually, I should have been more clear – it doesn't show trades that originate from him, but it shows instaProfit based on the sale price for him, while you obviously can't sell it to him when locked.

**Comment by dawidmachon** [comment]
It didn't make sense to disable such results from list - because you still can earn money on flea with such barters. InstaProfit is almost always lower than flea profit, so if we disable such results, you are loosing bigger opportunities.

**Comment by kokarn** [comment]
So it's the instaProfits on the start page, not the barters?

**Comment by Faalagorn** [comment]
Either the InstaProfit or Reward, yeah. I can't sell items to him if I don't have it unlocked :)

**Comment by kokarn** [comment]
Should be fixed with this https://github.com/kokarn/tarkov-tools/commit/be5e2a558c46a2eac3ae347fedb20b9fb5a79d60
