### ISSUE TITLE
Reset map zoom when changing map

### ISSUE THREAD

**Issue by kokarn** [kokarn/tarkov-tools#113]
Right now it keeps the zoom level of the last map

**Comment by mkim219** [comment]
Hi @kokarn. May I work on this issue?

**Comment by kokarn** [comment]
Hello 👋  
Of course! Anyone can work on anything they feel like :)

**Comment by mkim219** [comment]
Hi @kokarn. Would you please specify the issue? I click the one of the map and zoom-in then click the other map, the zoom level has already reset.

**Comment by kokarn** [comment]
What browser are you testing in? 
When I do this in Chrome the zoom doesn't reset when I change maps.

![chrome-capture (2)](https://user-images.githubusercontent.com/1373940/146535127-5685c1e9-427f-4de3-be84-aa77e9b7f937.gif)

**Comment by dawidmachon** [comment]
@mkim219 oh, I didn't see earlier your commit, sorry ;)
