### ISSUE TITLE
How to update missing info on website?

### ISSUE THREAD

**Issue by dawidmachon** [kokarn/tarkov-tools#114]
Hi, I just spotted some info are missing:
for example:
- [Pipe Grip Wrench](https://tarkov-tools.com/item/pipe-grip-wrench) - has section `Hideout modules needing Pipe grip wrench` empty but its not true, because as wiki said `Hideout - 1 needs to be obtained for the Booze generator`

How I could update these?

**Comment by kokarn** [comment]
All hideout data is fetched from [tarkovdata](https://github.com/TarkovTracker/tarkovdata/).

The best way to fix it on tarkov-tools is to add it there, then the whole community can benefit from it 👍

**Comment by kokarn** [comment]
Funnily enough this specific case was an unrelated error :) 
Fixed in this commit https://github.com/kokarn/tarkov-data-manager/commit/b9ca5febf09219dd854615c3b745f9d1737f4333

**Comment by dawidmachon** [comment]
thanks
