### ISSUE TITLE
Quest on item is not showed on web

### ISSUE THREAD

**Issue by dawidmachon** [kokarn/tarkov-tools#115]
Quest [Gratitude](https://escapefromtarkov.fandom.com/wiki/Gratitude) uses [Round sunglasses](https://escapefromtarkov.fandom.com/wiki/Round_frame_sunglasses) but on [website](https://tarkov-tools.com/item/round-frame-sunglasses) nothing is mentioned in section Quests.

**Comment by kokarn** [comment]
The reason for this is that it currently only shows quests where you have to turn in items, not stash them. Similar to fishing gear where you need a sv-98 and a leatherman.

Might make sense to show these as well tho now that you mention it

**Comment by dawidmachon** [comment]
For me, better show all, maybe additional section like turn in or stash. But all should be showed, because regardless of case you need such item ;)

**Comment by kokarn** [comment]
Yeah I agree 👍
