### ISSUE TITLE
Woods 5.2 map released, please add

### ISSUE THREAD

**Issue by Truesh00ter** [kokarn/tarkov-tools#122]
Woods 5.2 map released (0.12.12)

See: https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/05/Glory4lyfeWoods_map_v4_marked.png/revision/latest?cb=20211212154613

Can't make a pull request myself, having issues with my dev machine :(

**Comment by kokarn** [comment]
Thanks for the notification! Missed this with all the new changes going around :D

Sad to hear about the dev machine, but if you want it's possible to do it directly on Github for small things like this.

**Comment by kokarn** [comment]
So I updated Lighthouse yesterday... Was maybe a bit tired. Sorry about that! Woods 5.2 is now live :)

I was wrong about the edit on the GitHub interface as well. Apparently, they don't allow edits to images....

Thanks so much for reporting this <3
