### ISSUE TITLE
Fix Peacekeeper sell prices

### ISSUE THREAD

**Issue by kokarn** [kokarn/tarkov-tools#141]
Whenever you sell things to Peacekeeper he actually pays you in dollars. The "Sell to Trader" column should reflect that.

Here's a good example
https://tarkov-tools.com/traders/peacekeeper

**Comment by kokarn** [comment]
For this to be finished I think we need 2 improvements

1. Change the pipe `|` to a tippy tooltip

![image](https://user-images.githubusercontent.com/1373940/152500756-e3b6e612-eccf-42da-9fcf-795e089635e9.png)

2. Make sure it's displayed correctly all the time. For example, SAS drive has a weird sell for value

![image](https://user-images.githubusercontent.com/1373940/152500637-520021e4-9396-4535-b7a2-f5bcd1c96a8c.png)

@ATunaMelt You feel like this might be something for you?

**Comment by ATunaMelt** [comment]
Yup I’ll try to fix that today @kokarn

**Comment by kokarn** [comment]
Closed with #146
