### ISSUE TITLE
Some SVG icons are not vissible on Firefox

### ISSUE THREAD

**Issue by MysticalLatios** [kokarn/tarkov-tools#2]
Issue was while using Firefox 68.3.0esr, issue does not appear on chrome.

The svg icons are not visible for some of the calibers, when using the inspector I can see that the svg's are still part of the DOM.

![Screenshot_2019-12-23 Tarkov ammo chart](https://user-images.githubusercontent.com/11915655/71371381-cc6f6b00-2565-11ea-9488-d4db9bd3f3c8.png)

In this example the 5.45x39 is working:
`<svg width="2" height="2" fill="green" x="314" y="55.565000000000005" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"><path d=" M 100, 100 m -75, 0 a 75,75 0 1,0 150,0 a 75,75 0 1,0 -150,0 "></path></svg>`

Where the 5.45x45 is not working:

`<svg width="2" height="2" fill="green" x="314" y="62.18750000000001" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300"><path d="M0 225,L150 75,L300 225,Z"></path></svg>`

**Comment by kokarn** [comment]
I've done a lot of changes to the symbols, with the above commit fixing the last one. For me, all symbols work in Firefox now.

**Comment by kokarn** [comment]
Also, thanks so much for reporting!

**Comment by MysticalLatios** [comment]
No problem! Confirmed its working on my end now too! thanks for making this!

**Comment by kokarn** [comment]
No worries, need it myself :D
Hope you like the new icons :)
