### ISSUE TITLE
Recent update broke Tarkov Tools in Firefox

### ISSUE THREAD

**Issue by dsteinweg** [kokarn/tarkov-tools#3]
Hi, thanks for the great tool.

As of a few days ago (unsure exactly when), Firefox throws a JavaScript error when loading Tarkov Tools, visible in console:
TypeError: e.type.localeCompare is not a function

Unsure if it was a Firefox update or Tarkov Tools update.

**Comment by kokarn** [comment]
Thanks for reporting this!

Fixed it with https://github.com/kokarn/tarkov-tools/commit/1f2b61e7942a0d80dd840190427b305ed165b5cc
