### ISSUE TITLE
Loot-Tiers page disappears when no valid items exist

### ISSUE THREAD

**Issue by Kazilii** [kokarn/tarkov-tools#30]
Example: If you go to loot tiers and disable all of the filters, the entirety of the page disappears, and since it saves a cookie for your previous search terms, you need to delete your cookie in order to access the page again.

**Comment by kokarn** [comment]
Thanks a lot for reporting this!

This should be fixed as of 3 hours ago, with this commit https://github.com/kokarn/tarkov-tools/commit/86e7000d5eedcad334368230be445048bd3756a4

Do you still get that error?

**Comment by Kazilii** [comment]
Seems to be fixed! Thanks for the hard work <3

**Comment by kokarn** [comment]
Glad that it's resolved, and you're welcome!
