### ISSUE TITLE
Where is data.json?

### ISSUE THREAD

**Issue by colin-riddell** [kokarn/tarkov-tools#4]
Nice work on this tool. It's exactly what I was looking for. Was going to make some wee tweaks to it and submit PR.. but I noticed the data.json missing. 
Wondered why it's missing or if there's at least an example of it available?

Cheers

**Comment by colin-riddell** [comment]
Actually I think I've worked it out from the code. Thanks anyway

**Comment by kokarn** [comment]
Would love a PR for any changes at all. I'll update the readme on how to run it locally :)

**Comment by kokarn** [comment]
Added to the readme, thx for the unplanned suggestion :D
