### ISSUE TITLE
Implement "updated" field

### ISSUE THREAD

**Issue by Razzmatazzz** [kokarn/tarkov-tools#48]
It appears the "updated" field of the API is currently unimplemented as it always returns null. I assume the intent is for that field to indicate the date/time a particular item was last updated. Would be nice to have that implemented so it's easy to tell if I've already got the "freshest" data for an item without having to compare all the fields.

Awesome work on the API! Fantastic resource for the community.

**Comment by kokarn** [comment]
Tracked over here: https://github.com/kokarn/tarkov-data-api/issues/3
