### ISSUE TITLE
Sling backpack trader price missing

### ISSUE THREAD

**Issue by Hijacker** [kokarn/tarkov-tools#49]
Hi,

the Sling backpack does not recognize that it can be bought from Ragman LL1 at 2046 Roubles. Your database lists it as 8.8k Roubles. This also affects the Cordura craft, which is currently not profitable in your DB, but basing it on the 2k R Slings, it actually is profitable.

Cheers!

**Comment by kokarn** [comment]
Hey! Sorry for the slow response.

So right now there's no public list of which traders are selling what. The best public effort is this repo, https://github.com/TarkovTracker/tarkovdata/ but that doesn't contain what traders sell what.

The prices currently listed on the items pages are the prices traders are willing to buy for.

For sure a good enhancement would be calculate what items traders sell, but that requires more data.

**Comment by lipowskm** [comment]
@kokarn 
https://tarkov-market.com/ has this data actually. I was also thinking that this feature would be very helpful. I could prepare a scraper that checks prices of items needed for craft from their website, but I wonder what you think about such solution.

**Comment by kokarn** [comment]
I know they have some data, but that's also manually updated and curated by them. 
I'd rather have a proper public source instead of relying on another manual source :)

**Comment by lipowskm** [comment]
@kokarn
Yeah I thought so, but it was worth trying :D I was wondering if they are manually updating those prices or they have set up some bots that access BSG api, since I don't see any other solution for acquiring this data.

**Comment by kokarn** [comment]
I've had some discussions with them before and I'd wager it's a combination. Nobody's allowed to use their APIs saying straight out what they are doing tho :)

**Comment by lipowskm** [comment]
@kokarn

May I ask then how do you get prices in your API?

I didn't had a deep dive into it, and AFAIK there's no documentation yet, but I was wondering how do you get the base price and average price from the flee market. I know base price can be calculated from the buyback price, but still you need to get this data somehow.

**Comment by lipowskm** [comment]
@kokarn
Also don't get me wrong, I'm not trying to steal your knowledge or stuff like that, I was just wondering why is it possible to get the buyback price, but not the buy price itself.

**Comment by kokarn** [comment]
I use a network of bots running OCR scanners 24/7 to scan the whole Flea market :)

**Comment by kokarn** [comment]
And just a side note: you can ask me anything, no worries about that. 
I'll just decide what I share and what I don't. 
But sharing is caring, so rather have more openness than less.

**Comment by kokarn** [comment]
This change is now live
