### ISSUE TITLE
Max/min 24h price

### ISSUE THREAD

**Issue by Prillle** [kokarn/tarkov-tools#51]
I would like to see the maximum and lowest price an item is sold for the last 24h in the hideout profit page.

Prices are going up/down a lot during the day, so if i know that an item is sold for maximum 3000 rubles the last 24h i know that its stupid to sell it for 2000 right now because the demand is low.

Dont know if its a lot of work to code or if its possible at all :P

**Comment by kokarn** [comment]
Sounds like a nice feature 👍
