### ISSUE TITLE
Add levels of hideout modules needed for each craft

### ISSUE THREAD

**Issue by lipowskm** [kokarn/tarkov-tools#52]
Hi,

I would like to add information in the craft menu about the level of hideout module (workbench, lavatory etc.) needed for each craft. Also add some filtering basing on this.

If you are open for contributions I can create pull request for that, although I have pretty basic experience in React.

**Comment by kokarn** [comment]
I'm very open both to pull requests and the feature in particular! Sounds like a great addition :)

**Comment by lipowskm** [comment]
@kokarn PR created
https://github.com/kokarn/tarkov-tools/pull/53

**Comment by kokarn** [comment]
Closed with #53
