### ISSUE TITLE
In Hideout Profit, in cost, consider barter price

### ISSUE THREAD

**Issue by Shebuka** [kokarn/tarkov-tools#57]
In Hideout Profit include barter when considering the lowest price for components cost.

As example to craft Ripstop cloth you need 3x Scav Vest:

it's 3 X 20 220 ₽ = 60 660 ₽ for Flea market
but only 3 X 9 616 ₽ = 28 848 ₽ if bought as barter for Slickers bar

this turns the negative -18 680 ₽ in a 13 132 ₽ profit which is the best profit among Lavatory crafts.

**Comment by kokarn** [comment]
Thanks for the suggestion! This has been discussed a few times in Discord, and it's for sure a great idea.

Right now I'm mostly missing a good way to display this before I can start implementing it.

Some questions: 
* How to handle "limited" barters such as [Labs keycard](https://tarkov-tools.com/item/terragroup-labs-access-keycard)?
  * A small * to denote "this trade _might_ be unavailable because of stock"?


* How to handle barters locked behind loyalty levels?
   * Probably just the level dropdown in place today
   
* How to handle barters locked behind quests?

**Comment by Shebuka** [comment]
The easiest way I think is to add a switch like with fuel to switch on or off the barter consideration and add a tooltip with the caveats about barter. That it can be locked behind stock or quest (loyalty level can be filtered as you say by level dropdown that is already in place)

**Comment by kokarn** [comment]
So in the case of the keycard where there's multiple barters available, which should be used for calculations?
The cheapest? 
The most "probable"?
The one with the highest requirements?

In this image, what would you say the expected "price" for the keycard in the UHF RFID Reader craft would be?
![image](https://user-images.githubusercontent.com/1373940/121178321-a70c1500-c85e-11eb-9471-f134fb5877e4.png)

**Comment by Shebuka** [comment]
On Hideout profit page always the cheapest available.
On the item page there can be one or two entries: flea cost/profit and, if barter cost is lower, a barter cost/profit. Or keep one entry and add the barter switch here too.

The barter symbol (the two arrows in circle) can be used to indicate that one (or more) components are from the barter on both pages for the cost column.

<img width="1216" alt="TarkovTools" src="https://user-images.githubusercontent.com/10927011/121185895-d030a380-c866-11eb-9135-e36d4f6cdc67.png">

**Comment by kokarn** [comment]
I like it!

**Comment by Shebuka** [comment]
Switch and one entry version:

<img width="1217" alt="TarkovToolsSwitch" src="https://user-images.githubusercontent.com/10927011/121187002-e55a0200-c867-11eb-8810-b6f704c3a41a.png">

**Comment by kokarn** [comment]
This actually looks damn well. I've started working on this with the API changes first

**Comment by kokarn** [comment]
WIP
![Screenshot 2021-06-14 at 15 32 39](https://user-images.githubusercontent.com/1373940/121900554-d2db3f00-cd25-11eb-9f17-14f8f57eeab7.png)

**Comment by kokarn** [comment]
So in the first iteration I only calculated barter prices that are 1-1, so slickers bar etc. Looking at it now, it kinda doesn't make sense to do it that way so will probably do another pass where I add multiple ones.

One thing to note tho is that _all_ of those prices will be misleading when the wipe is in full swing, as labs card for gp coins etc are always sold out
