### ISSUE TITLE
"Tarkov loot tiers" wrong per slot price for guns

### ISSUE THREAD

**Issue by Shebuka** [kokarn/tarkov-tools#59]
As the title says, in "Tarkov loot tiers" guns are often considered to occupy one or two slots, while in reality, they occupy many more. This messes up per slot price and makes them included in loot tiers where they not belong. 
If the idea is to show what guns to loot as the second weapon then they must have their separate group. 
Or at least they all must occupy one slot because there is no logic behind why a "Mk-18 .338 LM marksman rifle" is two slots and a "Remington R11 RSASS 7.62x51" is one slot...

**Comment by kokarn** [comment]
Thanks! So the issue is that the data BSG provides tells you this
```
            "Name": "Mk-18 .338 LM marksman rifle",
            "Width": 2,
            "Height": 1,
```

Basically, a "gun" is only the receiver which is 2x1 big.
I could solve this easily by just hiding guns short term while trying to figure out a proper solution

**Comment by Shebuka** [comment]
If there no way to have assembled gun size then a separate section will all the guns will be optimal.

**Comment by kokarn** [comment]
After some internal discussion with @razzmatazzz we came up with the solution to use the default presets for guns to determine their size. This is now live!

Thanks for reporting this.

**Comment by Shebuka** [comment]
Have you rolled this back? I see again weapons be considered as one or two slots...

**Comment by kokarn** [comment]
This _should_ only apply to guns for which we haven't added the presets yet, and hence can't calculate the proper size for them.
I know this is an issue for the Mk47 but there are a few more that have the same problem apparently. 

Will investigate.

**Comment by kokarn** [comment]
Found the issue and fixed the issue. Basically all items renamed with the latest patch and the preset names were not updated yet.

Looks all good now!

**Comment by Shebuka** [comment]
Have you pushed to live already? I still see "Remington R11 RSASS 7.62x51 marksman rifle" as one slot Tier S loot.

**Comment by kokarn** [comment]
Yeah, it's live. 

Now there's still work to improve so that every gun has a preset, which isn't the case yet but we're working on it.

Will also do a pass to fix some broken images

**Comment by kokarn** [comment]
Also found a bug where some items had been removed from the game. That's also fixed now so RSASS should be the right size in a few minutes
