### ISSUE TITLE
Create a twitch bot

### ISSUE THREAD

**Issue by kokarn** [kokarn/tarkov-tools#74]
Pretty self-explanatory. Would be nice to have a twitch bot to give people

**Comment by cademack** [comment]
I think I might be willing to help with this. What kind of features did you have in mind? and did you have a language in mind for it? I've seen people use Python, C#, NodeJS, and a few others I think.

**Comment by kokarn** [comment]
Basic thing would be item lookup but after that the sky is the limit i
guess 🙂

There's already a framework started by @razzmatazzz here
https://github.com/Razzmatazzz/tarkov-tools-discord-bot which might help.

For me js would be most comfortable.

What do you think? What would be most interesting for you?

**Comment by athaller** [comment]
Just wanted to note that GraphQL could be used in this spot, Nightbot and other bots support making API requests. I'm just not sure how flexible it would be to format the output via Nightbot vs Phantom, etc

**Comment by kokarn** [comment]
That sounds very interesting. I would like there to be tarkov-tools integrations for pretty much any bot used if possible :) Do you have any experience with say Phantom?

**Comment by kokarn** [comment]
This is actually live now for both [nightbot](https://tarkov-tools.com/nightbot/) and [StreamElements](https://tarkov-tools.com/streamelements/)
