### ISSUE TITLE
Hideout Profit "Flea? - off"

### ISSUE THREAD

**Issue by Shebuka** [kokarn/tarkov-tools#85]
What is the idea behind this switch?
1) If it's to check if something you can craft you can sell for more to traders vs the flea market, I think this must be always considered even if the switch is on
2) If it's to indicate that you have no access to the flea market (very actual with lvl 20 access to the flea market) then it's better to calculate the "cost" using the price you'd otherwise sell the components to traders (vs using them to craft something that combined gives you good profit)

Now it's working as 1) option, but I'd suggest it to work like the 2) option and make the calculations for selling to traders even if you have access to the flea market.

**Comment by kokarn** [comment]
Yeah, i agree. The option was added quickly for the wipe so need to improve some calculations to make more sense
