### ISSUE TITLE
Strange cost and price mismatch (Flea/barter?)

### ISSUE THREAD

**Issue by Shebuka** [kokarn/tarkov-tools#86]
Hello,
so I was looking for Hideout Profit and something strange is happening right now with Gas Analyzer: https://tarkov-tools.com/item/gas-analyzer

![Screenshot 2021-07-21 at 13 02 22](https://user-images.githubusercontent.com/10927011/126482391-2b4d7e59-82f3-4bdd-b01d-a84c389cf7f0.png)

Currently, it's "sell for" **14 000 ₽** and "buy for" **14 874 ₽**

But if you look at barter for "MP9 9x19 30-round magazine" it says cost is **24 729 ₽** (also same cost as a component for Grizzly medical kit, also same cost as CPU Fan 🤔)

More strangely, if you look at crafts of "Printed circuit board" it suggests doing barter with "CPU Fan" for **19 000 ₽**... but you can buy it directly from flea for **14 874 ₽**!

**Comment by kokarn** [comment]
It's not _quite_ as strange as it seems. It's very bad UX tho.

Basically, all those three prices are calculated differently.

Buy & sell for uses average from last 24 hours, while barters & crafts don't.

Crafts also looks for barters for a better price, while barters don't look for "chain"-barters, which it should.

I'll work on making this a lot clearer 😓

**Comment by Shebuka** [comment]
I still think there is something wrong in the calculation or sort of results. 

- For barter "MP9 9x19 30-round magazine", where is 24 729 ₽ picked from? I don't see any place it mentions this, and why does "CPU Fan" cost **exactly** the same? (note: It's the "buy for" price of "CPU Fan" but there is no mention to do barter there)

- To craft "Printed circuit board" it suggests doing barter of "CPU Fan" for "Gas analyzer", "CPU Fan" costs 19 000 ₽ but "Gas analyzer" itself is 14 874 ₽ "@ Flea market"... it's wrong to suggest doing barter when you can buy it directly from Flea for cheaper (both sell and buy prices are actually cheaper than of CPU fan), and by extension, it is showing a wrong Estimated profit.

**Comment by kokarn** [comment]
> For barter "MP9 9x19 30-round magazine", where is 24 729 ₽ picked from?
It's from "average from the last 24 h" which is not displayed anywhere else.

> Barter calculation thing
That's the same thing I'm afraid, it's displaying one value and calculating another. It's calculating vs the 24 729 value where 19 000 is chaper.

Thanks for digging. 

I'll have another look when going over all the crafts & values to make sure there's nothing funky going on but I will also make sure to use the same display value so it's intuitive.

**Comment by Shebuka** [comment]
> It's from "average from the last 24 h" which is not displayed anywhere else.

I get it. My point is, I don't think it is of "Gas analyzer" because it is impossible that it is **exactly** the same average as for "CPU Fan".  I don't know how it happened but it is somehow displaying the barter for "CPU Fan" with the image of "Gas analyzer" and/or without realizing that it's a barter... And by having this mixed up then also craft cost and profit comparison with alternatives are mixed up.

> Thanks for digging.

Glad to help 😉 👍

**Comment by kokarn** [comment]
Working on improvements right now. Here's the current progress. Apart from using "buyFor" or "sellFor" values. do you spot anything else that seems off?

![image](https://user-images.githubusercontent.com/1373940/126775962-a5933a14-2c7c-444a-9666-ba881812793f.png)

**Comment by kokarn** [comment]
Actually pushed this, so will be live in a few minutes. Please try to find inconsistencies where a available 👍

**Comment by Shebuka** [comment]
I see, now the prices I think are all right.

But there is no indication when the price displayed is for the component bartered for something (like the Scav vest for Slickers when crafting Ripsoft fabric)

<img width="1223" alt="Screenshot 2021-07-23 at 14 40 05" src="https://user-images.githubusercontent.com/10927011/126783036-a3bc6b2d-adf4-4d1c-b3a3-41a5fca11d56.png">
<img width="1221" alt="Screenshot 2021-07-23 at 14 40 36" src="https://user-images.githubusercontent.com/10927011/126783039-f29e40ff-74db-4c91-96ba-bb890e50ce1f.png">

**Comment by Shebuka** [comment]
This is also strange, "Printed circuit board" craft, the price is calculated correctly, but then it shows in the sum to be from "CPU Fan"

<img width="1216" alt="Screenshot 2021-07-23 at 14 45 39" src="https://user-images.githubusercontent.com/10927011/126783663-702b9ae4-2589-4f21-89a3-b93823f0394a.png">

**Comment by kokarn** [comment]
All of these are now looking fixed when I'm investigating. Also includes #49

**Comment by Shebuka** [comment]
Hi, me again. Wilston cigarettes must be a 2,3k profit craft using 42nd Signature Blend English Tea barter, why it's using the buyFor cost?

<img width="1212" alt="Screenshot 2021-08-24 at 12 10 00" src="https://user-images.githubusercontent.com/10927011/130599103-ea73725f-d969-4afa-94da-627e31d101fd.png">

**Comment by kokarn** [comment]
Yeah, this is an old thing when I initially added so only barters that were 1-1 would be counted as a suggested barter. I've updated that locally and should be fixed with the next push
