### ISSUE TITLE
Zibbo lighter price is gone == 0

### ISSUE THREAD

**Issue by Shebuka** [kokarn/tarkov-tools#88]
Currently, the price of Zibbo lighter https://tarkov-tools.com/item/zibbo-lighter in "sell for" is 0 and there is no "buy for" price

**Comment by kokarn** [comment]
This is caused by a few bots crashing so no new flea prices have been added. Will be fixed very soon 👍

**Comment by Shebuka** [comment]
I suggest that if the bot crashes you keep stored the old prices and not overwrite them with 0 (or don't accept 0 as price returned from API).

**Comment by kokarn** [comment]
There's the catch of the calculations using only the last 24h of data, but yeah, there's some improvements in the works
