### ISSUE TITLE
Wrong sell price and trader not buying

### ISSUE THREAD

**Issue by Shebuka** [kokarn/tarkov-tools#92]
Hi,
found a discrepancy in the selling price of https://tarkov-tools.com/item/health-resort-west-wing-room-222-key, the toll says it sells for 66 546 ₽ at Therapist, but its actual price is 31 500 ₽... It was supposedly an InstaProfit but now I'm down 60k... Also, Jaeger is not buying it.

Another item that is listed https://tarkov-tools.com/item/serdyukov-sr-1mp-gyurza-9x21-pistol for Mechanic for 10 803 ₽ but its actual price is 11 4XX ₽ and Jaeger is also not buying it.

**Comment by kokarn** [comment]
There's a discussion going on in the Discord about this, as BSG recently did a big change to keys.

The trader sell prices for keys are updated and now says Therapist @ 31 500.

The pistol I'll have to dig deeper to know what's up. Thanks for reporting 👍

**Comment by kokarn** [comment]
Jaeger doesn't buy pistols. Fixed with https://github.com/kokarn/tarkov-data-manager/commit/ad13518b3a76fb039229c413a988bf649517c868
