### ISSUE TITLE
Most names of ammo is mismatched

### ISSUE THREAD

**Issue by vladimircreative** [kokarn/tarkov-tools#93]
I.e.: **7.62x54R PS**, instead of **7.62x54R 7H1**

**Comment by vladimircreative** [comment]
Oh, that might be the localization mismatch then. There's no "PS" ammo of that caliber on Russian version of the game.

**Comment by kokarn** [comment]
Yeah, that's a thing I'm working on. Adding all the localized names of items to the game.

Sorry for the confusion.

It's tracked here #70
